---

  - name: Build Arista Spine Configuration
    hosts: eos-spine
    connection: local
    gather_facts: no

    tasks:
      - name: BUILD CONFIGURATION1
        template:
          src=templates/eos-spine.j2
          dest=configs/{{ inventory_hostname }}.conf
        tag: build-spine

      - name: PUSH CONFIGS
        napalm_install_config:
          hostname={{ inventory_hostname }}
          username={{ username }}
          password={{ pwd }}
          dev_os=eos
          config_file=configs/{{ inventory_hostname }}.conf
          commit_changes=true
          replace_config=false
          get_diffs=false
        tags: push-spine

  - name: Build Arista leaf Configuration
    hosts: eos-leaf
    connection: local
    gather_facts: no

    tasks:
      - name: BUILD CONFIGURATION2
        template:
          src=templates/eos-leaf.j2
          dest=configs/{{ inventory_hostname }}.conf
        tag: build-leaf

      - name: PUSH CONFIGS
        napalm_install_config:
          hostname={{ inventory_hostname }}
          username={{ username }}
          password={{ pwd }}
          dev_os=eos
          config_file=configs/{{ inventory_hostname }}.conf
          commit_changes=true
          replace_config=false
          get_diffs=false
        tags: push-leaf
