---

  - name: Build Arista Spine Configuration
    hosts: eos-spine
    connection: local
    gather_facts: no

    tasks:
      - name: BUILD CONFIGURATION
        template:
          src=templates/eos-spine.j2
          dest=configs/{{ inventory_hostname }}.conf
        tag: build-spine

      - name: PUSH CONFIGS
        eos_config:
          src: configs/{{ inventory_hostname }}.conf
        tags: push-spine

  - name: Build Arista leaf Configuration
    hosts: eos-leaf
    connection: local
    gather_facts: no

    tasks:
      - name: BUILD CONFIGURATION
        template:
          src=templates/eos-leaf.j2
          dest=configs/{{ inventory_hostname }}.conf
        tag: build-leaf

      - name: PUSH CONFIGS
        eos_config:
          src: configs/{{ inventory_hostname }}.conf
        tags: push-leaf
